version: "3"

services:

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: "zookeeper"
    networks:
      - kafka_network
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - ../volumes/zookeeper_data:/bitnami/zookeeper/data
      - ../volumes/zookeeper_logs:/bitnami/zookeeper/logs

  kafka1:
    image: 'bitnami/kafka:latest'
    container_name: "kafka1"
    networks:
      - kafka_network
    ports:
      - '9091:9091'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=INTERNAL://:9092,EXTERNAL_SAME_HOST://0.0.0.0:9091 #usado para conexão inicial
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://:9092,EXTERNAL_SAME_HOST://localhost:9091 #comunicação subsequente
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    volumes:
      - ../volumes/kafka_data_1:/bitnami/kafka

  kafka2:
    image: 'bitnami/kafka:latest'
    container_name: "kafka2"
    networks:
      - kafka_network
    ports:
      - '9093:9093'
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_LISTENERS=INTERNAL://:9092,EXTERNAL_SAME_HOST://0.0.0.0:9093 #usado para conexão inicial
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://:9092,EXTERNAL_SAME_HOST://localhost:9093 #comunicação subsequente
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    volumes:
      - ../volumes/kafka_data_2:/bitnami/kafka

networks:
  kafka_network:
    name: kafka_docker_network
